import React, {useEffect, useState} from 'react';
import {Activity, Paperclip, Plus, RefreshCw, Search, Trash2, ToggleLeft, ToggleRight, Upload} from 'lucide-react';
import {AssetService, ProjectService, localAssetUrl} from '../services/api';

export function AuthenticationConfiguration({project, disabled=false, onChanged}) {
  const [enabled,setEnabled]=useState(Boolean(project.face_auth_enabled));
  const [videoPath,setVideoPath]=useState(project.video_file_path||'');
  const [storagePath,setStoragePath]=useState(project.face_video_storage_path||'');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  useEffect(()=>{setEnabled(Boolean(project.face_auth_enabled));setVideoPath(project.video_file_path||'');setStoragePath(project.face_video_storage_path||'');},[project.id,project.face_auth_enabled,project.video_file_path,project.face_video_storage_path]);
  useEffect(()=>{if(videoPath||!storagePath||busy)return;let cancelled=false;setBusy(true);AssetService.restoreFaceVideo(storagePath,project.id).then(async result=>{if(cancelled||!result?.y4m_path)return;setVideoPath(result.y4m_path);await ProjectService.updateProject(project.id,{video_file_path:result.y4m_path,face_video_storage_path:storagePath});}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[project.id,storagePath,videoPath]);
  async function toggle(){setBusy(true);setError('');const next=!enabled;try{const saved=await ProjectService.updateProject(project.id,{face_auth_enabled:next});setEnabled(next);await onChanged?.(saved);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function uploadVideo(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy(true);setError('');try{const result=await AssetService.uploadFaceVideo(file,project.id);setVideoPath(result.y4m_path);setStoragePath(result.storage_path);const saved=await ProjectService.updateProject(project.id,{face_auth_enabled:true,video_file_path:result.y4m_path,face_video_storage_path:result.storage_path});setEnabled(true);await onChanged?.(saved);}catch(e){setError(e.message);}finally{setBusy(false);}}
  const preview=videoPath?localAssetUrl(`/api/videos/${videoPath.split(/[\\/]/).pop().replace('.y4m','.mp4')}`):'';
  return <div className="card p-5 space-y-4 border border-indigo-500/20 bg-gradient-to-br from-slate-900 to-slate-800 text-white"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-sm font-bold text-white">Authentication Configuration</h2><p className="text-xs text-slate-400 mt-1">Configure optional Face Verification and virtual media for this project.</p></div><button type="button" disabled={disabled||busy} onClick={toggle} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold ${enabled?'bg-indigo-600 text-white':'bg-slate-700 text-slate-300'}`}>{enabled?<ToggleRight size={16}/>:<ToggleLeft size={16}/>}Face Auth {enabled?'Enabled':'Disabled'}</button></div><div className="grid md:grid-cols-2 gap-3 text-xs"><div className="p-3 rounded-lg bg-slate-800/80 border border-slate-700"><p className="font-bold text-indigo-400 mb-1">Username / Email and Password Login</p><p className="text-[11px] text-slate-400">Use protected runtime variables for credentials in test steps.</p></div><div className="p-3 rounded-lg bg-slate-800/80 border border-slate-700"><p className="font-bold text-indigo-400 mb-1">Biometric Face Verification (Optional)</p><p className="text-[11px] text-slate-400">Use a prepared virtual-camera video for supported authentication flows.</p></div></div>{enabled&&<div className="p-4 rounded-xl border border-indigo-500/30 bg-slate-950/60 space-y-3"><p className="text-xs font-semibold text-indigo-300 flex items-center gap-1.5"><Activity size={13}/>Virtual Webcam Biometric Input Video (.mp4)</p>{preview&&<video controls muted preload="metadata" crossOrigin="anonymous" src={preview} className="w-full max-h-48 rounded-lg border border-slate-800 bg-black"/>}<label className="flex px-3 py-2 rounded-lg border border-slate-700 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold justify-center cursor-pointer gap-2"><Upload size={13}/>{preview?'Replace Video':'Upload Face Verification Test Video'}<input aria-label="Face verification video" type="file" accept="video/mp4" disabled={busy||disabled} onChange={uploadVideo} className="hidden"/></label>{busy&&<p className="text-xs text-indigo-300">Preparing and synchronizing video...</p>}{error&&<p className="text-xs text-amber-300">{error}</p>}</div>}</div>;
}

export function ProjectAssetLibrary({project, disabled=false}) {
  const [assets,setAssets]=useState([]);const [search,setSearch]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function load(){try{setAssets(await AssetService.getAssets(project.id));}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[project.id]);
  async function upload(event){const files=[...(event.target.files||[])];event.target.value='';if(!files.length)return;setBusy(true);setError('');try{const saved=[];for(const file of files)saved.push(await AssetService.uploadAsset(file,project.id));setAssets(old=>[...saved,...old]);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function remove(asset){if(!globalThis.confirm(`Delete ${asset.filename||asset.name}?`))return;setBusy(true);try{await AssetService.deleteAsset(asset.id);setAssets(old=>old.filter(item=>item.id!==asset.id));}catch(e){setError(e.message);}finally{setBusy(false);}}
  const visible=assets.filter(asset=>(asset.filename||asset.name||'').toLowerCase().includes(search.toLowerCase()));
  return <div className="w-full space-y-6"><div className="card p-6 flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-900/60 dark:bg-zinc-900/60 border border-slate-800"><div><div className="flex items-center gap-2"><Paperclip size={20} className="text-indigo-400"/><h2 className="text-lg font-black text-primary tracking-tight">Project Assets</h2><span className="badge badge-indigo text-xs">{assets.length} Assets</span></div><p className="text-xs text-secondary mt-1">Upload reusable documents, images, spreadsheets, and videos for this project's automated tests.</p></div><div className="flex flex-wrap items-center gap-3"><label className="input-field flex items-center gap-2 min-w-[220px]"><Search size={14}/><input aria-label="Search assets" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search assets..." className="bg-transparent outline-none w-full"/></label><label className="btn-primary cursor-pointer"><Plus size={15}/>Upload Assets<input aria-label="Upload project assets" type="file" multiple disabled={busy||disabled} onChange={upload} className="hidden"/></label></div></div><div className="card overflow-hidden border border-slate-800 shadow-xl"><div className="p-4 border-b border-slate-100 dark:border-zinc-800 flex items-center justify-between bg-slate-950/40"><h3 className="section-label">Uploaded Project Test Files</h3>{busy&&<span className="flex gap-2 text-xs text-indigo-400"><RefreshCw size={14} className="animate-spin"/>Uploading asset...</span>}</div>{error&&<p className="status-panel status-error m-4">{error}</p>}{!visible.length?<div className="empty-state"><Paperclip size={32}/><p>{assets.length?'No assets match your search.':'No Project Assets Uploaded Yet'}</p></div>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-slate-100 dark:border-zinc-800 text-muted uppercase text-[10px]"><th className="py-3 px-4">Asset Details</th><th className="py-3 px-4">Filename</th><th className="py-3 px-4">Type</th><th className="py-3 px-4">Actions</th></tr></thead><tbody>{visible.map(asset=><tr key={asset.id} className="border-b border-slate-100 dark:border-zinc-900"><td className="py-3.5 px-4 font-bold text-primary">{asset.filename||asset.name}</td><td className="py-3.5 px-4 text-slate-400">{asset.filename||asset.name}</td><td className="py-3.5 px-4"><span className="badge badge-indigo">{(asset.file_type||asset.type||'file').toUpperCase()}</span></td><td className="py-3.5 px-4"><button aria-label={`Delete ${asset.filename||asset.name}`} className="icon-button text-red-400" onClick={()=>remove(asset)}><Trash2 size={13}/></button></td></tr>)}</tbody></table></div>}</div></div>;
}

