import React,{useState} from 'react';
import {ACTIONS,EXPECTATIONS} from '../lib/testDefinition';
import {Plus,CheckCircle2,Edit3,Trash2} from 'lucide-react';

const EMPTY={action:'click',target:'',value:'',expected_type:'',expected_value:'',expected_target:'',critical:false};
export default function TestStepBuilder({steps,onChange}) {
  const [editingIndex,setEditingIndex]=useState(null);const [draft,setDraft]=useState(EMPTY);
  const field=(key,label,options)=><label className="text-xs font-semibold text-secondary space-y-1" key={key}>{label}{options?<select aria-label={label} className="input-field" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}>{options.map(value=><option value={value} key={value}>{value||'No check'}</option>)}</select>:<input aria-label={label} autoComplete="off" type={key==='value'&&/password|secret|token/i.test(draft.target)?'password':'text'} className="input-field" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</label>;
  const save=()=>{if(draft.action!=='wait'&&!draft.target.trim())return;onChange(editingIndex===null?[...steps,{...draft}]:steps.map((step,index)=>index===editingIndex?{...step,...draft}:step));setEditingIndex(null);setDraft(EMPTY);};
  const addVerification=()=>{setEditingIndex(null);setDraft({...EMPTY,action:'verify',expected_type:'text_visible'});};
  return <section className="step-builder space-y-4">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h4 className="font-bold text-primary">Structured step builder</h4><p className="text-xs text-secondary mt-1">Use visible labels or roles. Add an outcome check so the run can prove the workflow succeeded.</p></div><div className="flex gap-2"><button type="button" className="btn-ghost text-xs" onClick={addVerification}><CheckCircle2 size={14}/>Add outcome check</button><span className="badge badge-neutral">{steps.length} steps</span></div></div>
    <div className="step-editor-panel"><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{field('action','Action',ACTIONS)}{field('target','Target')}{field('value','Input value')}{field('expected_type','Expected type',['',...EXPECTATIONS])}{field('expected_value','Expected value')}{field('expected_target','Expected target (optional)')}</div><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mt-3"><label className="text-xs text-secondary flex gap-2"><input type="checkbox" checked={draft.critical} onChange={e=>setDraft({...draft,critical:e.target.checked})}/>Stop this test if the step fails</label><button type="button" className="btn-primary text-xs" disabled={draft.action!=='wait'&&!draft.target.trim()} onClick={save}><Plus size={14}/>{editingIndex===null?'Add step':'Apply changes'}</button></div></div>
    <ol className="space-y-2">{steps.map((step,index)=><li key={index} className="step-review-row"><span className="step-number">{index+1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm text-primary">{step.action}</strong>{(step.action==='verify'||step.expected_type)&&<span className="badge badge-success">Outcome check</span>}{step.critical&&<span className="badge badge-neutral">Required</span>}</div><p className="text-xs text-secondary break-words mt-1">{step.target||'Wait'}{step.value?` · ${/\{\{.+\}\}/.test(step.value)?'[runtime value]':step.value}`:''}</p>{step.expected_type&&<p className="text-xs text-emerald-500 mt-1">Expect {step.expected_type}: {step.expected_value||step.expected_target||step.target}</p>}</div><div className="flex gap-1"><button type="button" className="icon-button" aria-label={`Edit step ${index+1}`} onClick={()=>{setEditingIndex(index);setDraft({action:step.action,target:step.target||'',value:step.value||'',expected_type:step.expected_type||'',expected_value:step.expected_value||'',expected_target:step.expected_target||'',critical:!!step.critical});}}><Edit3 size={14}/></button><button type="button" className="icon-button text-red-400" aria-label={`Remove step ${index+1}`} disabled={steps.some(item=>item.depends_on?.length)} title={steps.some(item=>item.depends_on?.length)?'Remove dependencies in the CSV before deleting steps':''} onClick={()=>onChange(steps.filter((_,position)=>position!==index))}><Trash2 size={14}/></button></div></li>)}</ol>
    {!steps.length&&<div className="empty-state"><p>No steps yet</p><span>Add an action above or generate a draft from a browser recording or video.</span></div>}
  </section>;
}
